import type {NextPage} from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Simple blog
                </h1>
                <Link href='/posts'><a>Posts</a></Link>
                <Link href='/posts/new'><a>Add post</a></Link>
            </main>
        </div>
    )
}

export default Home
